# Generated by Django 3.2.9 on 2022-01-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='user_id',
            new_name='id',
        ),
    ]
