# Generated by Django 3.2.9 on 2022-01-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('dest_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_img', models.ImageField(upload_to='')),
                ('dest_place', models.CharField(max_length=50)),
                ('dest_desc', models.TextField()),
            ],
        ),
    ]
