# Generated by Django 3.2.9 on 2022-01-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest',
            old_name='dest_id',
            new_name='id',
        ),
    ]
