# Generated by Django 3.2.9 on 2022-01-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeimage',
            old_name='img_id',
            new_name='id',
        ),
    ]
